### ISSUE TITLE
GitHub License Query targets master branch

### ISSUE THREAD

**Issue by tthiery** [aaronpowell/dotnet-delice#3] opened 2019-08-28 19:08 UTC
My F# is not the best, so correct me if I am wrong, but I am in the impression that if a package in version 1.2 does not have a spdx identifier, it would query the master (maybe version 3.5) of GitHub repo resulting in a license statement which is okay for 3.5 but not for version 1.2.

This would leave the wrong impression that the license is checked despite it is not a certainity.

Awesome tool. I played with the idea of writing it but failed doing it. Thanks.

**Comment by aaronpowell** [comment] 2019-08-28 22:58
Yep that's a known challenge of the GitHub lookup. It'd be a lot more work to try and create a regex to detect a branch-other-than-master. In reality it'd be better for packages to move to the new format 😊

**Comment by aaronpowell** [comment] 2019-09-02 23:58
I'm going to close this as it's expected behavior and the preferred solution would be to get the dependency to supply license metadata correctly rather than using the legacy `licenseUrl` field.

**Closed as completed** 2019-09-02 23:57 UTC

**Comment by tthiery** [comment] 2019-09-03 05:49
That is misleading and dangerous. There could be a lice in your code after that. It invalidates the purpose of the tool. A warning might be a suitable way around it.

PS have you considered to just try the version as Tag? Would be a pretty small change trying to access the relevant branch. Of that fails, just give the master's license and warn about it.

**Comment by aaronpowell** [comment] 2019-09-03 06:16
This is more of a symptom of the way licensing has been handled with NuGet than anything else. Since the field in the nuspec points to a URL the contents of the URL can be changed any any point without the consumer being made aware. That was part of the catalyst to move away from `licenseUrl` and have the SPDX ID in the package itself.

`delice` _attempts_ to work around this by making some guesses, one of which is a primitive guess using the GitHub API. Yes, there are edge cases where it may get it wrong. My experience tells me that the number of packages that have relicensed between releases **and** have correctly updated the `licenseUrl` across each version with a detectable OSI/FSF license is **very** small, so the effort to support that scenario is higher than the value I foresee being obtained.

If someone wants to send a PR I'm happy to review and make a decision but for me _personally_ the ROI is low and thus isn't not something I'm concerned about.
